name       : gtkhash
version    : 1.1.1
release    : 6
source     :
    - https://github.com/tristanheaven/gtkhash/releases/download/v1.1.1/gtkhash-1.1.1.tar.xz : a18c09a6af5b26c79bda81ab8a1835679fefbf2b87f1df4858c42ad45729f6bf
license    : GPL-2.0-only
component  :
    - system.utils
    - caja-extension : desktop
    - nautilus-extension : desktop
summary    :
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
    - nautilus-extension : Nautilus extension for GtkHash
description:
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
    - nautilus-extension : Nautilus extension for GtkHash
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(nettle)
    - pkgconfig(nss)
rundeps    :
    - caja-extension : gtkhash
    - nautilus-extension : gtkhash
patterns   :
    - /*
    - caja-extension : [/usr/lib64/caja, /usr/share/appdata/caja*]
    - nautilus-extension : [/usr/lib64/nautilus, /usr/share/appdata/nautilus*]
setup      : |
    %configure \
        --disable-blake2 \
        --disable-glib-checksums \
        --disable-schemas-compile \
        --enable-nautilus \
        --enable-caja \
        --enable-linux-crypto \
        --enable-nettle \
        --enable-nls \
        --enable-nss
build      : |
    %make
install    : |
    %make_install
