name       : gtkhash
version    : '1.4'
release    : 12
source     :
    - https://github.com/tristanheaven/gtkhash/releases/download/v1.4/gtkhash-1.4.tar.xz : 20b57dbb8f6c6d7323f573c111a11640603a422c5f9da7b302a4981e4adc37c4
license    : GPL-2.0-or-later
component  :
    - system.utils
    - caja-extension : desktop
    - nautilus-extension : desktop
summary    :
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
    - nautilus-extension : Nautilus extension for GtkHash
description:
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
    - nautilus-extension : Nautilus extension for GtkHash
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(nettle)
    - pkgconfig(nss)
    - libgcrypt-devel
rundeps    :
    - caja-extension : gtkhash
    - nautilus-extension : gtkhash
patterns   :
    - /*
    - caja-extension : [/usr/lib64/caja, /usr/share/appdata/caja*]
    - nautilus-extension : [/usr/lib64/nautilus, /usr/share/appdata/nautilus*]
setup      : |
    %configure \
        --disable-blake2 \
        --disable-glib-checksums \
        --disable-schemas-compile \
        --enable-nautilus \
        --enable-caja \
        --enable-linux-crypto \
        --enable-nettle \
        --enable-nls \
        --enable-nss
build      : |
    %make
install    : |
    %make_install
