name       : gtkhash
version    : '1.1'
release    : 4
source     :
    - https://github.com/tristanheaven/gtkhash/releases/download/v1.1/gtkhash-1.1.tar.xz : c86b7d8dcfc00aad1cd6bc73fa7c5a18006fbd4ae1fa909d4b4a1e255ce5cfa2
license    : GPL-2.0
component  :
    - system.utils
    - caja-extension : desktop
summary    :
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
description:
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(nettle)
    - pkgconfig(nss)
rundeps    :
    - caja-extension : gtkhash
patterns   :
    - /*
    - caja-extension : [/usr/lib64/caja, /usr/share/appdata/caja*]
setup      : |
    %configure \
        --disable-glib-checksums \
        --disable-schemas-compile \
        --enable-caja \
        --enable-linux-crypto \
        --enable-nettle \
        --enable-nls \
        --enable-nss
build      : |
    %make
install    : |
    %make_install
