name       : gtkhash
version    : '1.5'
release    : 16
source     :
    - https://github.com/tristanheaven/gtkhash/releases/download/v1.5/gtkhash-1.5.tar.xz : 7102a192eca3e82ed67a8252a6850440e50c1dbea7c6364bda154ec80f8ff005
license    : GPL-2.0-or-later
component  :
    - system.utils
    - caja-extension : desktop
summary    :
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
description:
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(nettle)
    - pkgconfig(nss)
    - libgcrypt-devel
rundeps    :
    - caja-extension : gtkhash
patterns   :
    - /*
    - caja-extension : [/usr/lib64/caja, /usr/share/appdata/caja*]
setup      : |
    %configure \
        --disable-blake2 \
        --disable-glib-checksums \
        --disable-schemas-compile \
        --disable-nautilus \
        --enable-caja \
        --enable-linux-crypto \
        --enable-nettle \
        --enable-nls \
        --enable-nss
build      : |
    %make
install    : |
    %make_install
