name       : gtkhash
version    : 1.0
release    : 2
source     :
    - https://github.com/tristanheaven/gtkhash/releases/download/v1.0/gtkhash-1.0.tar.xz : ae1faac88a745953bba583c91173d08f8aab8153c30418b10ed43496ea561e45
license    : GPL-2.0
component  :
    - system.utils
    - caja-extension : desktop
summary    :
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
description:
    - A GTK+ utility for computing message digests or checksums
    - caja-extension : Caja extension for GtkHash
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(nettle)
    - pkgconfig(nss)
rundeps    :
    - caja-extension : gtkhash
patterns   :
    - /*
    - caja-extension : [/usr/lib64/caja, /usr/share/appdata/caja*]
setup      : |
    %configure \
        --disable-glib-checksums \
        --disable-schemas-compile \
        --enable-caja \
        --enable-linux-crypto \
        --enable-nettle \
        --enable-nls \
        --enable-nss
build      : |
    %make
install    : |
    %make_install
